apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: 9090
      targetPort: websocket
      protocol: TCP
      name: websocket
    - port: {{ .Values.monitoring.exporterPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
