apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appdaemon.fullname" . }}
  labels:
    {{- include "appdaemon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appdaemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "appdaemon.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "appdaemon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: git-sync-init
          image: "{{ .Values.gitsync.image.repository }}:{{ .Values.gitsync.image.tag }}"
          imagePullPolicy: {{ .Values.gitsync.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /config
          - name: git-secret
            mountPath: /etc/git-secret
          env:
          - name: GIT_SYNC_REPO
            value: "{{ .Values.gitsync.repo }}"
          - name: GIT_SYNC_BRANCH
            value: "{{ .Values.gitsync.branch }}"
          - name: GIT_SYNC_ROOT
            value: /config
          - name: GIT_SYNC_DEST
            value: "appdaemon-config.git"
          - name: GIT_SYNC_PERMISSIONS
            value: "0777"
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          securityContext:
            {{- toYaml .Values.gitsync.securityContext | nindent 12 }}
          resources:
{{ toYaml .Values.gitsync.resources | indent 12 }}
      containers:
        - name: git-sync
          image: "{{ .Values.gitsync.image.repository }}:{{ .Values.gitsync.image.tag }}"
          imagePullPolicy: {{ .Values.gitsync.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /config
          - name: git-secret
            mountPath: /etc/git-secret
          env:
          - name: GIT_SYNC_REPO
            value: "{{ .Values.gitsync.repo }}"
          - name: GIT_SYNC_BRANCH
            value: "{{ .Values.gitsync.branch }}"
          - name: GIT_SYNC_ROOT
            value: /config
          - name: GIT_SYNC_DEST
            value: "appdaemon-config.git"
          - name: GIT_SYNC_PERMISSIONS
            value: "0777"
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SYNC_WAIT
            value: "30"
          securityContext:
            {{- toYaml .Values.gitsync.securityContext | nindent 12 }}
          resources:
{{ toYaml .Values.gitsync.resources | indent 12 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "appdaemon", "-c", "/config/appdaemon-config.git" ]
          volumeMounts:
          - name: config
            mountPath: /config
          - name: tmp
            mountPath: /tmp
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: git-secret
        secret:
          #defaultMode: 288
          secretName: {{ .Values.gitsync.secretName }} # your-ssh-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
