{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appdaemon.serviceAccountName" . }}
  labels:
{{ include "appdaemon.labels" . | nindent 4 }}
{{- end -}}
