apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doods.fullname" . }}
  labels:
{{ include "doods.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "doods.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "doods.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: models-download-1
          image: busybox
          command: [ "wget", "-O", "/tmp/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite", "https://dl.google.com/coral/canned_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite"]
          volumeMounts:
          - name: models-volume
            mountPath: /tmp
        - name: models-download-2
          image: busybox
          command: [ "wget", "-O", "/tmp/coco_labels.txt", "https://dl.google.com/coral/canned_models/coco_labels.txt"]
          volumeMounts:
          - name: models-volume
            mountPath: /tmp            
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /detectors
              port: http
          readinessProbe:
            httpGet:
              path: /detectors
              port: http
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /dev/bus/usb
            name: usb
          - mountPath: /opt/doods/config.yaml
            name: config-volume
            subPath: config.yaml
          - mountPath: /opt/doods/models
            name: models-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: usb
          hostPath:
            path: /dev/bus/usb
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ include "doods.fullname" . }}
        - name: models-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
