apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pihole.fullname" . }}
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.pihole.webPassword }}
  web-password: {{ .Values.pihole.webPassword | b64enc | quote }}
  {{- else }}
  web-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}