apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.httpservice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: http
spec:
  type: {{ .Values.service.http.type }}
  {{- if eq .Values.service.http.type "LoadBalancer" }}
  {{- if .Values.service.http.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.http.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.http.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.http.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: 80
      protocol: TCP
      name: {{ .Values.service.http.name }}
    - port: {{ .Values.monitoring.exporterPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
