apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mikrotik-exporter.fullname" . }}
  labels:
    {{- include "mikrotik-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mikrotik-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mikrotik-exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mikrotik-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADDRESS
              value: {{ default "" .Values.config.address | quote }}
            - name: DEVICE
              value: {{ default "" .Values.config.device | quote }}
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "mikrotik-exporter.fullname" . }}
                  key: user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mikrotik-exporter.fullname" . }}
                  key: password
          ports:
            - name: http
              containerPort: 9436
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
