apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mikrotik-exporter.fullname" . }}
  labels:
    {{- include "mikrotik-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ default "" .Values.config.user | b64enc | quote }}
  password: {{ default "" .Values.config.password | b64enc | quote }}