apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.monitoring.exporterPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
