{{- if and (.Values.assistant.enabled) (.Values.assistant.ingress.enabled) }}
{{- $fullName := include "zigbee2mqtt.fullname" . -}}
{{- $ingressPath := .Values.assistant.ingress.path -}}
{{- $servicePort := .Values.assistant.service.port -}}
{{- $serviceName := printf "%s-%s" $fullName "assistant" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
{{- include "zigbee2mqtt.labels" . | nindent 4 }}
{{- if .Values.assistant.ingress.labels }}
{{ toYaml .Values.assistant.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.assistant.ingress.annotations }}
  annotations:
{{ toYaml .Values.assistant.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range .Values.assistant.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- if .Values.assistant.ingress.tls }}
  tls:
    {{- range .Values.assistant.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
{{- end -}}
{{- end }}
