{{- $fullName := include "zigbee2mqtt.fullname" . -}}
{{- $assistantContainerName := printf "%s-%s" $fullName "assistant" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zigbee2mqtt.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategyType }}
  template:
    metadata:
      labels:
        {{- include "zigbee2mqtt.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zigbee2mqtt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: "Europe/Berlin"
          volumeMounts:
          # - mountPath: /dev/ttyACM0
          #   name: tty
          - mountPath: /app/data
            name: datastore
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.assistant.enabled }}
        - name: {{ $assistantContainerName }}
          image: "{{ .Values.assistant.image.repository }}:{{ tpl .Values.assistant.image.tag . }}"
          imagePullPolicy: {{ .Values.assistant.image.pullPolicy }}
          env:
            - name: Z2MA_SETTINGS__MQTTSERVER
              value: {{ .Values.assistant.mqtt.server }}
            - name: Z2MA_SETTINGS__MQTTUSERNAME
              value: {{ .Values.assistant.mqtt.username }}
            - name: Z2MA_SETTINGS__MQTTPASSWORD
              value: {{ .Values.assistant.mqtt.password }}
            - name: ASPNETCORE_URLS
              value: "http://*:8880"
          {{ if .Values.assistant.baseTopic }}
            - name: Z2MA_SETTINGS__BASETOPIC
              value: {{ .Values.assistant.baseTopic }}
          {{ end }}
          {{ if hasKey .Values.assistant "haBaseTopic" }}
            - name: Z2MA_SETTINGS__HOMEASSISTANTDISCOVERYBASETOPIC
              value: {{ .Values.assistant.haBaseTopic }}
          {{ end }}
          {{ if hasKey .Values.assistant "lowBatteryThreshold" }}
            - name: Z2MA_SETTINGS__LOWBATTERYTHRESHOLD
              value: {{ .Values.assistant.lowBatteryThreshold }}
          {{ end }}
          {{ if hasKey .Values.assistant "allowJoinTimeout" }}
            - name: Z2MA_SETTINGS__ALLOWJOINTIMEOUT
              value: {{ .Values.assistant.allowJoinTimeout }}
          {{ end }}
          {{ if hasKey .Values.assistant "autosetLastSeen" }}
            - name: Z2MA_SETTINGS__AUTOSETLASTSEEN
              value: {{ .Values.assistant.autosetLastSeen }}
          {{ end }}
          {{ if hasKey .Values.assistant "pollingSchedule" }}
            - name: Z2MA_SETTINGS__DEVICESPOLLINGSCHEDULE
              value: {{ .Values.assistant.pollingSchedule }}
          {{ end }}
          {{ if hasKey .Values.assistant "netScanSchedule" }}
            - name: Z2MA_SETTINGS__NETWORKSCANSCHEDULE
              value: {{ .Values.assistant.netScanSchedule }}
          {{ end }}
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: http
              containerPort: {{ .Values.assistant.service.port }}
              protocol: TCP
          {{ end }}
      volumes:
        # - name: tty
        #   hostPath:
        #     path: /dev/ttyACM0
        - name: datastore
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "zigbee2mqtt.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
