
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
{{ include "blocky.labels" . | indent 4 }}
data:
{{- if .Values.config }}
{{ $root := . }}
  config.yml: |
{{ tpl (toYaml .Values.config | indent 4) $root }}
{{- end }}
{{- range $name, $value := .Values.extraLists }}
  {{ $name }}: |-
{{ $value | indent 4}}
{{- end }}
  whitelist.txt: |-
    mobile.pipe.aria.microsoft.com