apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blocky.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blocky.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        fluentbit.io/parser: json
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "blocky.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns-tcp
              containerPort: 8053
              protocol: TCP
            - name: dns-udp
              containerPort: 8053
              protocol: UDP
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /usr/bin/dig
              - "@127.0.0.1"
              - -p
              - "8053"
              - healthcheck.blocky
              - +tcp
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
              - /usr/bin/dig
              - "@127.0.0.1"
              - -p
              - "8053"
              - www.google.com
              - +tcp
            initialDelaySeconds: 5
            periodSeconds: 60
          volumeMounts:
          - mountPath: /app/config.yml
            name: config-volume
            subPath: config.yml
          - mountPath: /app/whitelist.txt
            name: config-volume
            subPath: whitelist.txt
          - mountPath: logs
            name: logs-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ include "blocky.fullname" . }}
        - name: logs-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
