apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.fullname" . }}-tcp
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
    app.kubernetes.io/component: "tcp-service"
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blocky.selectorLabels" . | nindent 4 }}
