apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: dns-tcp
    #   protocol: TCP
    #   name: dns-tcp
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "blocky.selectorLabels" . | nindent 4 }}
